w4/w4d5/reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, only: [:new, :create, :destroy, :edit, :update, :index, :show]
  resources :posts, only: [:new, :create, :destroy, :edit, :update, :show] do
    resources :comments, only: [:new, :create, :show]
  end



end

w4/w4d5/reddit/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author, :post, :content, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post
end

w4/w4d5/reddit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to post_url(Post.find_by(id: params[:post_id]))
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
    render :show
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

w4/w4d5/reddit/app/helpers/comments_helper.rb
module CommentsHelper
end

w4/w4d5/reddit/app/views/comments/new.html.erb
<h1>Create Comment</h1>

<form action="<%= post_comments_url %>" method="post">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="content">Content</label>
  <textarea name="comment[content]" rows="8" cols="80"></textarea>

  <input type="submit" value="Submit Comment!">
</form>

w4/w4d5/reddit/app/views/comments/show.html.erb
<h1>Show!</h1>