w4/w4d5/reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, only: [:new, :create, :destroy, :edit, :update, :index, :show]
  resources :posts, only: [:new, :create, :destroy, :edit, :update, :show] do
    resources :comments, only: [:new, :create, :show]
  end



end

w4/w4d5/reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base

  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User,
    inverse_of: :subs

  has_many :posts, through: :post_subs, source: :post

  has_many :post_subs, inverse_of: :sub, dependent: :destroy

end

w4/w4d5/reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def new
    @sub = Sub.new
    render :new
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
      # flash[:errors] = @sub.errors.full_messages
      # redirect_to new_sub_url
    end
  end

  def edit
    update
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if logged_in?
      # user is logged in and is mod of sub
      if @sub.moderator_id == current_user.id
        @sub.update_attributes(sub_params)
      else
        flash[:notice] = "Can't update other people's subs"
      end
    else
      flash[:notice] = "Not logged in; please login"
      redirect_to new_session_url
    end
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    @sub.destroy
    @sub
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end
end

w4/w4d5/reddit/app/helpers/subs_helper.rb
module SubsHelper
end

w4/w4d5/reddit/app/views/subs/new.html.erb
<h1>Create Sub!</h1>

<form action= "<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="title">Sub Name</label>
  <input type="text" name="sub[title]" value="title">

  <br><br>
  <textarea name="sub[description]" rows="8" cols="80">Description</textarea>

  <br>
  <input type="submit" value="Create Sub!">

</form>

w4/w4d5/reddit/app/views/subs/show.html.erb
<h1>Profile Page!</h1>

<h2><%= @sub.title %></h2>
<p>Description: <%= @sub.description %></p>

<% @sub.posts.each do |post| %>
  <%= post.title %>
<% end %>